version: '3'

networks:
  rustdesk-net:
    external: false

services:
  hbbs:
    container_name: hbbs
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r ${HOST_IP}:21117 
    volumes:
      - ./data:/root 
    
    networks:
      - rustdesk-net
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    ports:
      - 21117:21117
      - 21119:21119
    image: rustdesk/rustdesk-server:latest
    command: hbbr 
    volumes:
      - ./data:/root
    networks:
      - rustdesk-net
    restart: unless-stopped
  pubkey-server:
    container_name: pubkey-server
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./data:/usr/share/nginx/html:ro
    networks:
      - rustdesk-net
    restart: unless-stopped
